#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lucene-QueryParser
version:      1.04
version_from: QueryParser.pm
installdirs:  site
requires:
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
